[package]
name = "rd2qmd-mdast"
description = "mdast types and Quarto Markdown writer for rd2qmd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[dev-dependencies]
serde_json.workspace = true
